#!bin/bash
#by :WHITE TERMUX
#clear
echo -e "\e[1;36m"
sleep 1
echo   "  /\                         |\**/|"
echo   " /  \                        \ == / "
echo   " |  |                         |  | "
echo   "/ == \                        \  / "
echo   "|/**\|                         \/  "
echo ""
sleep 1

echo "HTTP INJECTOR"
echo ""
sleep 1
echo "GENERANDO PAYLOAD"
echo ""
sleep 1
echo " █▀▀█ █▀▀█ █▀▀▀ █▀▀█ █▀▀▄ █▀▀▀█ █▀▀█   █░▒█ █▀▀█ █▀▀█ █░▄▀ █▀▀▀ █▀▀▄   █▀▀█ █▀▀▄
 █░░░ █▄▄▀ █▀▀▀ █▄▄█ █░▒█ █░░▒█ █▄▄▀   █▀▀█ █▄▄█ █░░░ █▀▄░ █▀▀▀ █░▒█   █▄▄█ █░▒█
 █▄▄█ █░▒█ █▄▄▄ █░▒█ █▄▄▀ █▄▄▄█ █░▒█   █░▒█ █░▒█ █▄▄█ █░▒█ █▄▄▄ █▄▄▀   █░▒█ █▄▄▀ "
echo ""
sleep 1
echo "WHITE TERMUX"
sleep 2
echo "WHITE TERMUX"
echo ""
echo "PAYLOAD"
echo "facebook.com"
echo ""
sleep 1
echo -ne "\e[1;36mρσɳ ƭµ ɦσรƭ: \e[1;33m"
read host
echo ""

echo "GENERANDO PAYLOAD"
sleep 2
echo ""
echo "CONNECT [host_port]GET $host HTTP/1/1[crlf] [protocol][crlf] [protocol][crlf][crlf]"

echo ""
echo ""
echo "GENERANDO PAYLOAD"
sleep 2
echo ""
echo "GET $host HTTP/1.0[crlf][cr|f][sp|it_delay][method] $host@[host_port][protocol][crlf][crlf]"

echo ""
echo "GENERANDO PAYLOAD"
sleep 2
echo ""
echo "CONNECT [host_port][split]GET $host HTTP/1.1[lf][lf]"

echo ""

echo "GENERANDO PAYLOAD"
sleep 2
echo ""
echo "GET $host HTTP/1.0[crlf][cr|f][sp|it_delay][method] $host@[host_port][protocol][crlf][crlf]"
echo ""

echo "GENERANDO PAYLOAD"
sleep 2
echo ""
echo "GET $host HTTP/1.1[crlf] ٌُْْ[crlf][crlf]CONNECT [host_port][delay_split][crlf]"

echo ""
echo "GENERANDO PAYLOAD"
sleep 2
echo ""
echo "CONNECT  $host@[host_port] [protocol][split]HEAD $host HTTP/1.1[crlf]Host:$host[crlf][crlf]"

echo ""
echo "GENERANDO PAYLOAD"
sleep 2
echo ""
echo "OPTIONS $host HTTP/1.1[crlf]Host: $host[crlf][crlf]CONNECT [host_port] [protocol][crlf][crlf]"

echo ""
echo "GENERANDO PAYLOAD"
sleep 2
echo ""
echo "CONNECT [host_port]@$host [protocol][crlf][instant_split]GET $host HTTP/1.1[crlf]Host: $host[crlf][crlf]"
echo ""
echo ""echo "GENERANDO PAYLOAD"
sleep 2
echo ""
echo "CONNECT [host_port] [protocol][crlf]Host: $host[crlf][crlf]"

echo ""
echo "GENERANDO PAYLOAD"
sleep 2
echo ""
echo "TRACE $host HTTP/1.0 Host:$host Connection: Keep-Alive [crlf]"


echo ""
echo "GENERANDO PAYLOAD"
echo ""
sleep 2
echo "HEAD HTTP/[crlf] [crlf]Host: $host[crlf] [crlf]"

echo ""
echo "GENERANDO PAYLOAD"
echo ""
sleep 2
echo "CONNECT $host@[host_port] HTTP/1.1[crlf][crlf]GET $host [protocol][crlf]Host: $host[crlf]X-Forwarded-For: $host[crlf]Connecti                   >

echo ""
